### ISSUE TITLE
It looks like you're using the development build of the Firebase JS SDK

### ISSUE THREAD

**Issue by kokarn** [TarkovTracker/TarkovTracker#13]
```
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the CDN builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

https://www.gstatic.com/firebasejs/5.0.0/firebase-<PACKAGE>.js
```

![image](https://user-images.githubusercontent.com/1373940/122742809-9f993280-d286-11eb-89ff-183b9ba89a53.png)

**Comment by thaddeus** [comment]
Interesting. I haven't (intentionally) changed anything with the SDK since my last major work on the site in April. You're right though, I see that on production as well. I'm specifically not using the CDN SDK due to how I create different instances of the site depending upon whether the user wants to utilize it 'offline' (localstorage) or 'online' (Firebase). I'll have to look into this tomorrow evening, thanks for the heads up!
