### ISSUE TITLE
Map tabs total tasks per map not respecting hide global tasks option

### ISSUE THREAD

**Issue by ageorgewarren** [TarkovTracker/TarkovTracker#424]
If I select the "Hide global tasks in map view" option the global tasks are hidden but the bubble number over map name does not reflect this. So on woods I have one woods specific task I only see one on the bottom but 8 at the top.

![image](https://github.com/TarkovTracker/TarkovTracker/assets/37959732/e6ae13e1-c393-45c2-bc45-4b3303eba856)

**Comment by georgi-huklev** [comment]
Furthermore map objectives marked as completed are still being counted:
![image](https://github.com/TarkovTracker/TarkovTracker/assets/8859641/70b250b7-50eb-441e-a398-10a90883f3f2)

**Comment by DysektAI** [comment]
> Furthermore map objectives marked as completed are still being counted: ![image](https://private-user-images.githubusercontent.com/8859641/337975358-70b250b7-50eb-441e-a398-10a90883f3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjI1NDcsIm5iZiI6MTcxOTE2MjI0NywicGF0aCI6Ii84ODU5NjQxLzMzNzk3NTM1OC03MGIyNTBiNy01MGViLTQ0MWUtYTM5OC0xMGE5MDg4M2YzZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjNUMTcwNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YzNzY4ZTk4ZTQ4ODgwM2QxZDlhYTQ3NzhkNzJmN2IyZTc3MTViYWVlZjRmOGE0ZmZhYWIxMDlhNTIzZTY5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.00mVwG8kDnxH3LXETbec1tob5-YKf6yPxkbJYqfVH1g)

This is due to how this metric is designed instead of using the count of objectives for the map it uses the number of **Tasks** left for that map so its displaying properly in your instance this would be a feature request.

**Comment by geohuk** [comment]
> > Furthermore map objectives marked as completed are still being counted: ![image](https://private-user-images.githubusercontent.com/8859641/337975358-70b250b7-50eb-441e-a398-10a90883f3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjI1NDcsIm5iZiI6MTcxOTE2MjI0NywicGF0aCI6Ii84ODU5NjQxLzMzNzk3NTM1OC03MGIyNTBiNy01MGViLTQ0MWUtYTM5OC0xMGE5MDg4M2YzZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjNUMTcwNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YzNzY4ZTk4ZTQ4ODgwM2QxZDlhYTQ3NzhkNzJmN2IyZTc3MTViYWVlZjRmOGE0ZmZhYWIxMDlhNTIzZTY5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.00mVwG8kDnxH3LXETbec1tob5-YKf6yPxkbJYqfVH1g)
> 
> This is due to how this metric is designed instead of using the count of objectives for the map it uses the number of **Tasks** left for that map so its displaying properly in your instance this would be a feature request.

This is not what I mean. If a task has all objectives for a map done, it should not be counted. https://github.com/TarkovTracker/TarkovTracker/pull/426 already fixes that.

**Comment by DysektAI** [comment]
> > > Furthermore map objectives marked as completed are still being counted
> 
> > 
> 
> > This is due to how this metric is designed instead of using the count of objectives for the map it uses the number of **Tasks** left for that map so its displaying properly in your instance this would be a feature request.
> 
> 
> 
> This is not what I mean. If a task has all objectives for a map done, it should not be counted. https://github.com/TarkovTracker/TarkovTracker/pull/426 already fixes that.

Okay misunderstood what you were referring to in your original post that's a nice improvement after reviewing the PR it seems correct.

My misunderstanding was, I thought you were referring to when marking an objective as complete on a task, it was not updating and reflecting the badge count decreasing (which requires completing the task itself). Now I realize you are filtering by tasks per map and filtering out global tasks, but when marking the last objective complete it's not removing it from the map and still displays the "X amount of objectives on other maps". 

I did notice this also but it didn't bother me too much, I usually prioritized maps with the highest task count remaining instead. 

What I did want to fix, was so that if you mark all objectives completed it would either "automatically complete" the task without also clicking "completed", or at minimum have a small confirmation modal pop up over the task card. A quick call to action making it quick and easy to complete tasks by completing all objectives.

After a while the objectives seemed obsolete to me and instead just completed when done fully with tasks. Since the objectives only helped with tasks that have a lot of steps or tedious objectives like the "farming" quests. 

(Which those also were a pain since it's not possible to track the quantity of items in the objectives on the task list. It's just simply a Boolean finished or not)

So if you want a fun challenge @r-gruber try making the objectives like "hand over 4 GPU's" capable of setting the amount of items turned in or handed over so far in the task list:
`0/4 GPU's (0%)`
`2/4 GPU's (50%)`
`4/4 GPU's (100% Completed)`

Would help a lot!
